[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "librosa==0.10.1",
    "numpy==1.24.3",
    "soundfile==0.12.1",
    "tensorflow==2.14.0",
]
